### ISSUE TITLE
GitCloneError when running a job

### ISSUE THREAD

**Issue by wjchulme** [opensafely/job-runner#55]
Trying to run a job on this repo https://github.com/opensafely/os-demo-research (yaml [here](https://github.com/opensafely/os-demo-research/blob/master/project.yaml)) in this workspace http://jobs.opensafely.org/jobs/?workspace=4, but it fails with 

```
GitCloneError: git pull --depth 1 os-demo-research master id job#465
```` 
see job here http://jobs.opensafely.org/api/jobs/465/

The requested action on this job was `run_all` but the same error occurs if just using `generate_cohort`.

**Comment by evansd** [comment]
The repo need to be the full URL, rather than just the name. If you look at the workspaces page here you should be able to see the issue:
http://jobs.opensafely.org/workspaces/

There doesn't seem to be a way to edit workspaces at the moment though. You could just create a new one. Or maybe @ghickman can fix in directly in the database for you.

**Comment by ghickman** [comment]
Arg, yes, that's correct, sorry!

I've fixed that in Production and once I get opensafely/job-server#92 done you won't see the issue again.

@wjchulme – Could you confirm the fixed repo field fixes the issue for you?

**Comment by wjchulme** [comment]
Ah good spot. Thanks for sorting. It's re-running now and taking much longer than it ever did so I assume it's sorted. Will close once it finishes.
